# Generated by Django 2.1.3 on 2018-11-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='toode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=999)),
                ('price', models.CharField(max_length=9)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
