# Generated by Django 2.1.3 on 2018-11-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_toode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toode',
            name='lang',
            field=models.CharField(max_length=3),
        ),
    ]
