# Generated by Django 2.1.3 on 2018-11-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_auto_20181115_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='toode',
            name='prevprice',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
