# Generated by Django 2.1.3 on 2018-11-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_toode_prevprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='toode',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='toode',
            name='protsent',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='toode',
            name='lang',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='toode',
            name='name',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='toode',
            name='prevprice',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='toode',
            name='price',
            field=models.CharField(default='', max_length=9),
        ),
    ]
