# Generated by Django 2.1.3 on 2018-11-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0005_auto_20181120_1526'),
        ('browser', '0005_auto_20181120_1329'),
    ]

    operations = [
    ]
