# Generated by Django 2.1.3 on 2018-11-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0006_merge_20181123_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='browser_lang',
            name='kaibeMaks',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AddField(
            model_name='browser_lang',
            name='saadavausPoes',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AddField(
            model_name='browser_lang',
            name='uusHind',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AddField(
            model_name='browser_lang',
            name='vanaHind',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AddField(
            model_name='toode',
            name='laoseis',
            field=models.BooleanField(default=True),
        ),
    ]
