# Generated by Django 2.1.3 on 2018-11-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0008_auto_20181126_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browser_lang',
            name='kaibeMaks',
            field=models.CharField(default='', max_length=999),
        ),
    ]
