# Generated by Django 2.1.3 on 2019-04-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0009_auto_20181126_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toode',
            name='laoseis',
        ),
    ]
