# Generated by Django 2.1.3 on 2019-04-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0010_remove_toode_laoseis'),
    ]

    operations = [
        migrations.AddField(
            model_name='toode',
            name='esilehele',
            field=models.BooleanField(default=False),
        ),
    ]
