# Generated by Django 2.1.3 on 2019-04-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0012_remove_toode_protsent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toode',
            name='esilehele',
        ),
        migrations.AddField(
            model_name='toode',
            name='Esilehele: y/n',
            field=models.CharField(default='', max_length=1),
        ),
    ]
