# Generated by Django 2.1.3 on 2019-04-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0013_auto_20190415_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toode',
            old_name='Esilehele: y/n',
            new_name='esilehele',
        ),
    ]
