# Generated by Django 2.1.3 on 2019-04-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0014_auto_20190415_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='browser_lang',
            name='enne',
            field=models.CharField(default='', max_length=999),
        ),
    ]
