# Generated by Django 2.1.3 on 2019-04-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0015_browser_lang_enne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toode',
            name='esilehele',
            field=models.CharField(default='', max_length=1, verbose_name='esilehele y/n'),
        ),
    ]
