# Generated by Django 2.1.3 on 2019-05-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0016_auto_20190416_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toode',
            name='esilehele',
            field=models.CharField(default='n', max_length=1, verbose_name='esilehele y/n'),
        ),
    ]
