# Generated by Django 2.1.3 on 2019-11-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0017_auto_20190501_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='browser_lang',
            name='bg_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
