# Generated by Django 2.1.3 on 2019-11-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0018_browser_lang_bg_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='browser_lang',
            name='header',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='browser_lang',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='browser_lang',
            name='h1',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
