# Generated by Django 2.1.3 on 2019-11-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0019_auto_20191102_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browser_lang',
            name='enne',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='browser_lang',
            name='kaibeMaks',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='browser_lang',
            name='saadavausPoes',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='browser_lang',
            name='uusHind',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='browser_lang',
            name='vanaHind',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='toode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='toode',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='toode',
            name='lang',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='toode',
            name='name',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='toode',
            name='prevprice',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='toode',
            name='price',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
