# Generated by Django 2.2.9 on 2020-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0020_auto_20191103_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='toode',
            name='toode_id',
            field=models.CharField(default='', max_length=999),
        ),
    ]
