# Generated by Django 2.2.9 on 2020-04-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0021_toode_toode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='toode',
            name='specs',
            field=models.TextField(blank=True),
        ),
    ]
