# Generated by Django 2.1.3 on 2018-11-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181119_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='kalender_priority',
            field=models.CharField(choices=[('M', 'midagi'), ('V', 'vaatamine'), ('L', 'lisamine'), ('K', 'muutmine')], default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='worker',
            name='tookoda_priority',
            field=models.CharField(choices=[('M', 'midagi'), ('V', 'vaatamine'), ('L', 'lisamine'), ('K', 'muutmine')], default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='worker',
            name='varuosad_priority',
            field=models.CharField(choices=[('M', 'midagi'), ('V', 'vaatamine'), ('L', 'lisamine'), ('K', 'muutmine')], default='', max_length=999),
        ),
    ]
