# Generated by Django 2.2.9 on 2020-04-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_worker_kirjad_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='tolked_priority',
            field=models.CharField(choices=[('M', 'midagi'), ('V', 'vaatamine'), ('L', 'lisamine'), ('K', 'muutmine')], default='', max_length=999),
        ),
    ]
