# Generated by Django 2.1.3 on 2018-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meist_lang',
            name='asukoht',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AddField(
            model_name='meist_lang',
            name='pilt',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='meist_lang',
            name='tekst',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='meist_lang',
            name='h1',
            field=models.CharField(default='', max_length=999),
        ),
    ]
