# Generated by Django 2.1.3 on 2018-12-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutlang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=99999, unique=True)),
                ('meist', models.CharField(max_length=99999)),
                ('kaardil', models.CharField(max_length=99999)),
                ('kaardil2', models.CharField(max_length=99999)),
                ('kontakt', models.CharField(max_length=99999)),
                ('kontakt2', models.CharField(max_length=99999)),
                ('kontakt_nimi', models.CharField(max_length=99999)),
                ('kontakt_tel', models.CharField(max_length=99999)),
                ('kontakt_mail', models.CharField(max_length=99999)),
                ('kontakt_sisu', models.CharField(max_length=99999)),
                ('saada', models.CharField(max_length=99999)),
            ],
        ),
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=99999)),
                ('tel_nr', models.CharField(max_length=99999)),
                ('e_mail', models.CharField(max_length=99999)),
                ('letter', models.TextField(max_length=99999)),
            ],
        ),
    ]
