# Generated by Django 2.1.3 on 2019-04-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meist', '0003_meist_lang_msg'),
        ('meist', '0003_auto_20181229_2312'),
    ]

    operations = [
    ]
