# Generated by Django 2.1.3 on 2019-04-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meist', '0004_merge_20190414_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meist_lang',
            name='asukoht',
        ),
        migrations.RemoveField(
            model_name='meist_lang',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='meist_lang',
            name='pilt',
        ),
        migrations.RemoveField(
            model_name='meist_lang',
            name='tekst',
        ),
    ]
