# Generated by Django 2.1.3 on 2019-04-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meist', '0005_auto_20190414_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='meist_lang',
            name='h1',
            field=models.CharField(default='', max_length=99999),
        ),
    ]
