# Generated by Django 2.1.3 on 2018-11-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kalender_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=999)),
                ('paev', models.CharField(max_length=999)),
                ('tundide_arv', models.CharField(max_length=999)),
                ('kes_tegi', models.CharField(max_length=999)),
            ],
        ),
    ]
