# Generated by Django 2.1.3 on 2018-11-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='varuosad_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(max_length=999)),
                ('nimi', models.CharField(max_length=999)),
                ('kontakt', models.CharField(max_length=999)),
                ('automark', models.CharField(max_length=999)),
                ('varuosade_kood', models.CharField(max_length=999)),
                ('nimetus', models.CharField(max_length=999)),
                ('hind', models.CharField(max_length=999)),
                ('kogus', models.CharField(max_length=999)),
                ('tellitud_kuup', models.CharField(max_length=999)),
                ('saabus_kuup', models.CharField(max_length=999)),
                ('valja_kuup', models.CharField(max_length=999)),
                ('ettemaks', models.CharField(max_length=999)),
                ('aeg', models.CharField(max_length=999)),
                ('kes_tegi', models.CharField(max_length=999)),
            ],
        ),
    ]
