# Generated by Django 2.2.9 on 2020-04-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varuosad', '0002_google_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='varuosad_entry',
        ),
    ]
